spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  logging:
    leve:
      org:
        hibernate:
          SQL: debug
          type: trace